services:
  - type: web
    name: expense-tracker
    env: docker
    plan: free
    healthCheckPath: /api/expenses/
    envVars:
      - key: SECRET_KEY
        scope: run
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: expense-tracker.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    databaseName: expensetracker
    user: postgres
    plan: free
